name: Hello World!

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
      run: | 
        echo "Hello World!"
  
  log_now:
    runs-on: ubuntu-20.04
    steps:
      - name: log now
      run: |
        date -r

  log_ls
    runs-on: ubuntu-20.04
    steps:
      -name: step1
      run: |
        ls -l;
